### ISSUE TITLE
[API] API-ify Soul Cage so integration with other mods is easier.

### ISSUE THREAD

**Issue by TehNut** [TehNut-Mods/Soul-Shards-The-Old-Ways#12]
Requested by @ProfessorProspector for https://github.com/TechReborn/TechReborn

**Comment by Prospector** [comment]
well probably more for an addon but yes.

**Comment by Prospector** [comment]
Preferably I could just extend a BaseCage and tell it when to handle the mob spawning. Something like canSpawn() and I could return true if it has enough energy and stuff.

**Comment by TehNut** [comment]
Well I assume you would want to be able to modify speed as well

**Comment by Prospector** [comment]
ah yes, that too. I also need to add a Nicolas Soul Cage that is super fast :P

**Comment by TehNut** [comment]
I'm not sure how feasible doing it all through the API is. But I can move some checks into their own methods. So you'd extend `TileEntityCage` and override `getCooldown()` (to change spawn speed), `getSpawnAmount()` (to change amount of mobs spawned), and `canSpawn()` (if spawning is allowed). Other than those three methods (and any helper methods you need for your own stuff), the rest should be able to be left untouched.

http://paste.ubuntu.com/15623779/

**Comment by Prospector** [comment]
Yeah, looks good.
