### ISSUE TITLE
[1.8.9] Spawners crashes server, conflict with Spongeforge

### ISSUE THREAD

**Issue by Xiaminou** [TehNut-Mods/Soul-Shards-The-Old-Ways#15]
Server crashes when I activate a wither skeleton spawner.

Crash report: http://pastebin.com/g96eaCPy

**Comment by TehNut** [comment]
Could you try updating SpongeForge? They are currently on build 1395 while you are on 1336. If that doesn't work, I'd report it to them. They're doing some weird casting shenanigans on their end.

**Comment by TehNut** [comment]
Any news?

**Comment by Xiaminou** [comment]
updating to spongeforge-1.8.9-1890-4.2.0-BETA-1421 fixed it.
