### ISSUE TITLE
[1.9.4] Enchanted Book for Soul Stealer lacks Description

### ISSUE THREAD

**Issue by Laruae** [TehNut-Mods/Soul-Shards-The-Old-Ways#16]
#### What happens:

When Soul Stealer I is enchanted onto a book the description for the enchantment is missing from the book. It reads "Format Error: Press your LSHIFT key to see a description of the first enchantment."

![image 1](https://cloud.githubusercontent.com/assets/10898219/16318437/38a38dae-395d-11e6-99df-ae4d3777a597.png)

When pressing Shift, the following is displayed. "Format error: No description could be found. Please ask the author of the Soul Shards - The Old Ways mod to add one. The localization key is **description.enchantment.soulStealer**"

![image 2](https://cloud.githubusercontent.com/assets/10898219/16318436/38a36c34-395d-11e6-8826-0ecdbd4a12b3.png)
#### What you expected to happen:

Vanilla minecraft enchantments on books read out their descriptions when moused over while holding shift. The format error line is added by Minecraft and may be a change in how the enchantment descriptions are formatted in 1.9.4 as even the vanilla enchantments appear to have them.
#### Steps to reproduce:
1. Enchant book with Soul Stealer
2. Mouse over enchanted book
3. Shift + mouse over enchanted book
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- Soul Shards: SoulShards-TOW-1.9.4-2.4.4-32
- Minecraft: 1.9.4
- Forge: 12.17.0.1.1968

**Comment by TehNut** [comment]
I'll support this, but who adds the tooltip? You should report the format error to them.

**Comment by Laruae** [comment]
> I'll support this, but who adds the tooltip? You should report the format error to them.

The tooltip is being added by [WAWLA.](http://mods.curse.com/mc-mods/minecraft/224712-wawla-what-are-we-looking-at#t1:other-downloads) 

Currently using ver. Wawla-1.9.4-2.2.1.192.
