### ISSUE TITLE
Can't craft Vile Dust - have Natrua installed

### ISSUE THREAD

**Issue by AbieTheFishman** [TehNut-Mods/Soul-Shards-The-Old-Ways#17]
#### Issue Description:

Not a bug 
#### What happens:

I have Natura installed - so get "Soule Glass" when smelting soul sand.

Is the a work around.
#### Steps to reproduce:
1. 
2. 
3. 
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- Soul Shards: SoulShards-TOW-1.7.10-0.1-RC9-7.jar
- Minecraft: 1.7.10
- Forge:

**Comment by TehNut** [comment]
I do not maintain nor support the 1.7.10 version of the mod.
