### ISSUE TITLE
[Complaint] About your limits.

### ISSUE THREAD

**Issue by DrZed** [TehNut-Mods/Soul-Shards-The-Old-Ways#18]
Your limits in the mod, quite well annoy me, I'm grabbing the sauce code, and modifying it for my pack.
1.) ID limit is completely barbaric. Minecraft alone supports 255 as max ID and mods extend those IDs, I have mine extending to 512 (I add 50 enchants), Reika extends it, BOP extends, and many others do as well. I wanted to set the ID to 250~ because I had over 240 enchants loaded in my pack, and had to move crap around because I like mod enchant IDs to be in the same area.

2.) Your limit on kills for your shards, 2048 is easy AF, hell I looked at my endermen killed count on my recent pack ~8000 of which was 2.3 days total played. I was going to set the tiers in powers of 2 starting at 128, but that idea got shot in the foot as well.

**Comment by TehNut** [comment]
1. They are not my limits.
2. You are using 1.7.10. That is _extremely_ old and unsupported.
