### ISSUE TITLE
Soul Shards vs. TiCon

### ISSUE THREAD

**Issue by Chinthor** [TehNut-Mods/Soul-Shards-The-Old-Ways#19]
#### Issue Description:

The modpack is "Fear the Dark" (not to be confused with "Fear of the Dark")
This issue was posted with them first, still waiting on a response.
The issue is that, while TiCon lists Vile tools and weapons as existing, they cannot be made.
#### What happens:

JEI lists Vile and Corrupted tools and tool parts, but I cannot make the parts. I can't melt corrupted ingots or tool parts. There is not liquid for them to melt into. I cannot craft the parts in a part builder.
#### What you expected to happen:

I expect the ingots to melt for casting or there to be a material that can go in the part builder.
#### Steps to reproduce:
1. craft a handful of corrupted ingots 
2. try to make any of the TiCon parts listed in JEI
3. Fail
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- Soul Shards: 2.5.0 - 34
- Minecraft: 1.10
- Forge: 12.18.0.2000

**Comment by Chinthor** [comment]
Cool. Thank you. But, uhm. Now the mod wants minecraft 1.10.2 only. What?

**Comment by TehNut** [comment]
Build running
