### ISSUE TITLE
TCon Soul Stealer Modifier

### ISSUE THREAD

**Issue by TehNut** [TehNut-Mods/Soul-Shards-The-Old-Ways#2]
Material required = Shard?

**Comment by Phonavis** [comment]
Yes... It's all you have to say, Just Yes.

**Comment by TehNut** [comment]
On hold until TCon updates to 1.9. Then I'll start taking a look.

**Comment by TehNut** [comment]
https://gfycat.com/HighlevelFamousCreature

(base kill + modifier level)

**Comment by TehNut** [comment]
9d11f717093a2e5ec905a3a857e5e567df698b0d
