### ISSUE TITLE
Request: Allow inversion of redstone behavior

### ISSUE THREAD

**Issue by utoc** [TehNut-Mods/Soul-Shards-The-Old-Ways#20]
This is not a bug, just a humble request from the perspective of a server owner.

Previous versions had the following config line:
    B:"Invert Redstone"=false

I would like to request, if possible, that this ability be reinstated.  I understand that the consequences mean all tier configs will have to use  
    "checkRedstone": true

Thank you for your consideration and for porting this mod to current

**Comment by TehNut** [comment]
To clarify, you want a blanket config option that forces the Cage to require a redstone signal in order to spawn, correct?

**Comment by TehNut** [comment]
Default vs Config functionality: https://streamable.com/ck1n

Not going to close or release until you confirm this is what was intended.

**Comment by utoc** [comment]
Yes, this is what I intended.  Thats awesome, thank you

**Comment by TehNut** [comment]
coolio

**Comment by utoc** [comment]
Tested today, working as intended.  Thanks again :)
