### ISSUE TITLE
Soul Cage not spawning

### ISSUE THREAD

**Issue by AlphaChimaera89** [TehNut-Mods/Soul-Shards-The-Old-Ways#24]
#### Issue Description:

Soul Cage does not light up or spawn mobs when given a soul shard
#### What happens:

Soul Cage does not light up or spawn mobs when given a soul shard
#### What you expected to happen:

I expected it to spawn mobs, as it had been doing previously
#### Steps to reproduce:
1. Place Soul Cage
2. Put Soul Shard in Soul Cage
3. Wait...
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- Soul Shards:  SoulShards-TOW-1.10.2-2.5.3-37
- Minecraft: 1.10.2
- Forge: 12.18.0.2010

**Comment by TehNut** [comment]
Do you happen to play something related to @utoc? He recently requested a config option (#20) to require the Soul Cage to be receiving a Redstone Signal.

**Comment by AlphaChimaera89** [comment]
I don't know @utoc, and im not sure what he plays. I am on a private 1.10.2 pack called Donutcraft. We recently updated to your recent version, and the cage stopped functioning. I will test a redstone signal and see if that works.

**Comment by TehNut** [comment]
With a default config, I am unable to reproduce this issue. Can you make sure that `forceRedstoneRequirement` didn't get enabled?

**Comment by TehNut** [comment]
Nevermind. Only T5 shards are currently working... w0t

**Comment by AlphaChimaera89** [comment]
Lol yeah. That's what the other dev mentioned. I broke your block with a
modded tool and crashed out, so I sent off a report to that guy also. He
pointed to this line:
https://github.com/Ellpeck/ActuallyAdditions/blob/1.9.4/src/main/java/de/ellpeck/actuallyadditions/mod/util/WorldUtil.java#L399

**Comment by AlphaChimaera89** [comment]
Woops sorry, wrong link. The line in your code is here:
https://github.com/TehNut/Soul-Shards-The-Old-Ways/blob/1.10/src/main/java/com/whammich/sstow/block/BlockCage.java#L59

**Comment by TehNut** [comment]
I pointed that out to him.

**Comment by AlphaChimaera89** [comment]
Wow I really need to check names!
