### ISSUE TITLE
Feature Request: Textures for Soul Shard Tiers beyond 5

### ISSUE THREAD

**Issue by Divineaspect** [TehNut-Mods/Soul-Shards-The-Old-Ways#25]
We're using soulshards for 1.8.9, with the plan of including it in a pack.
When playing with the altered configs for soul shards we discovered that the textures for soul shards do not extend to the full possible range.

**Comment by TehNut** [comment]
You must ship your own blockstate json and textures.

**Comment by belathus** [comment]
would I put the custom blockstate.json file in the ./config/sstow folder?

**Comment by TehNut** [comment]
A resource pack

**Comment by belathus** [comment]
I've had little success with this. I tried copy/pasting the tier 5 entry in the json, editing the "5" to "6" or higher, but I still see no textures, even with a resource pack.
