### ISSUE TITLE
Ghost entities limiting mob count

### ISSUE THREAD

**Issue by misterg1** [TehNut-Mods/Soul-Shards-The-Old-Ways#27]
#### Issue Description:

I made a level 4 soul shard of zombie pigmans to feed my blood altar's well of suffering. After some time, baby zombie pigman entities are flying without any motion in the room around the spawner. They can be attacked but don't attack back and can't be killed (half a heart remains). Trying to remove all zombie pigman entities with /kill @e[type=PigZombie] removes some of them visually. The spawnrate nevertheless stays low as if they were still there. Also the adjacent blocks around the soul cage are blocked for building - even after removing the soul cage.
Reloading the world removes all ghost entities and the spawner works as intended again.
#### Steps to reproduce:
1. Kill 512 Zombie Pigman to get a level 4 soul shard
2. Build a soul cage in 9x9x5 room (inside dimensions) in the very middle of the room (height: 3)
3. Place the soul shard in it and let them spawn
4. Kill the entities with a well of suffering from blood magic
5. Wait for a while (the first ghost entities appeared after about half an hour, after about 6 hours only one zombie spawned from the cage at a time)

---
#### Affected Versions (Do _not_ use "latest"):
- Soul Shards: 1.10.2-2.5.5-39
- Minecraft: 1.10.2
- Forge: 12.18.1.2016

**Comment by TehNut** [comment]
I found out about this originally [here](https://www.reddit.com/r/feedthebeast/comments/4ug8fa/weird_issue_with_soulshards_1102/). I have been looking, but not entirely sure why its happening.

**Comment by misterg1** [comment]
Yeah this picture shows exactly the behaviour I noticed.. For now I will just create a new soul shard with another mob type hoping that they behave ;)

**Comment by belathus** [comment]
Hm. I've had little success getting textures to show up for tiers 6+. I tried copy/pasting the previous tiers and just changing the "5" to a "6" (and higher) and reusing the same texture, but I've had zero success.

**Comment by TehNut** [comment]
IT'S WHEN THEY TRY TO SPAWN AS A CHICKEN JOCKEY

That took way too much debugging to find out >.> Now, _why_ does that happen? :confounded: 

Edit: I think I fixed it. Or at least, put a bandaid on it.
