### ISSUE TITLE
Tier 5 Spawner Stops Working - Sort Of

### ISSUE THREAD

**Issue by Utildayael** [TehNut-Mods/Soul-Shards-The-Old-Ways#28]
#### Issue Description:

Tier 5 Spawner bound to Zombie Pigman seems to run fine for 5-10 minutes then mysteriously goes out to lunch. 
#### What happens:

T5 spawner stops spawning as expected. During this time I see chickens spawn but no pigmen. If I log off the server, wait about 5 minutes for things to unload, and come back I see a bunch of the small pigmen. Adding the small part as the full size ones are never present, only the small ones. I kill all of them but the spawner still acts "weird" and spawns chickens until I either log off for a long time [30 min] or the server is rebooted. Last time this happened, admin told me the server memory was pegged which was abnormal. Note that no one was online at the time and baseline performance was 25% or less memory in use.

Note that I was using EnderIO redstone wires to feed redstone signal to the spawner and using an EnderIO Killer Joe to kill the pigmen so it wasn't hitting the spawn cap or anything like that as it was keeping up with killing the pigmen as they spawned.
#### What you expected to happen:

Spawner to continue spawning. Did not have this issue with T1-T4 of the spawner as I was leveling up the soul shard [kept swapping between two]. Once I got to T5 ran into this issue.
#### Steps to reproduce:
1. Make T5 zombie pigman shard
2.  Place in spawner
3.  Wait 5-10 minutes
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- Soul Shards: SoulShards-TOW-1.10.2-2.6.1-41 
- Minecraft: 1.10.2
- Forge:  12.18.1.2050

Thanks!

**Comment by TehNut** [comment]
I think this is fixed by 0d2569dd7c0350c7bf76c3d13a0e694bc072e9cc which I actually forgot I had committed locally.

**Comment by Utildayael** [comment]
Sweet! You da man sir!

**Comment by TehNut** [comment]
Should be live on Curse. Let me know if there's any continued issues.

**Comment by Utildayael** [comment]
Even better!  Thanks again
