### ISSUE TITLE
Crash RandomThings related

### ISSUE THREAD

**Issue by Gamewalker** [TehNut-Mods/Soul-Shards-The-Old-Ways#32]
Hey,

I updated my mods and I get an crash now, I dunno if its on your end or RandomThings end:

https://gist.github.com/Gamewalker/480843edd70ce07a73b887d27ea0932f
#### Issue Description:

Server doesn't start anymore. throwing exception
#### What happens:

Server doesn't start anymore. throwing exception
#### What you expected to happen:

Server to start?
#### Steps to reproduce:

---
#### Affected Versions (Do _not_ use "latest"):
- Soul Shards: 2.6.3-43
- Minecraft: 1.10.2
- Forge: 2095

**Comment by TehNut** [comment]
Delete the block at `-122,74,240`. Somehow you managed to set a Cage to a Potion Vaporizer (whatever that is) without the Cage's Tile Entity being removed.

**Comment by Gamewalker** [comment]
Hm, I will test some world backups. I never made a Potion Vaporizer :)

**Comment by Gamewalker** [comment]
ok, seems like a corrupted world was the problem.
