### ISSUE TITLE
Soul shard stack is improperly handled when interaction with a Soul Cage

### ISSUE THREAD

**Issue by Aaron1011** [TehNut-Mods/Soul-Shards-The-Old-Ways#33]
In [`BlockCage#onInteract`](https://github.com/TehNut/Soul-Shards-The-Old-Ways/blob/9750b8/src/main/java/com/whammich/sstow/block/BlockCage.java#L154), the `ItemStack`'s size is decremented by 1. However, the `ItemStack` is never offered back to the player's hand. This code is only working because an `ItemSoulShard`'s max stack size is 1 - since it will always be decremented to 0, Forge will detect this and set `null` into the player's hand. However, this would not work for other stack sizes.

For compatibility [with Sponge](https://github.com/SpongePowered/SpongeForge/issues/943), which doesn't expect this kind of behavior, it would be nice if you could either:
- Offer the itemstack back to the player's hand.
- Handle interactions through either `Item#onItemUse` or `Block#onBlockActivated`, which already properly handle changes in the `ItemStack`.

**Comment by TehNut** [comment]
I should not need to "offer the itemstack back" as I am using the same object. This is valid behavior.

Edit: If you are breaking Forge behavior, I don't see why this is my fault.

**Comment by Aaron1011** [comment]
> I should not need to "offer the itemstack back" as I am using the same object. This is valid behavior.

Not really - it only works because you always end up setting the size to 0. If you look at `PlayerInteractionManager#processRightClickBlock`, the stack is never set back into the player's hand at all. The only reason it's happening in your case is because `NetHandlerPlayServer#processRightClickBlock` handles `ItemStacks` of size 0 specially.

> Edit: If you are breaking Forge behavior, I don't see why this is my fault.

Sponge is technically changing Forge behavior, but this is really more of a quirk of Forge's `RightClickBlock` than anything else. Were the initial size anything other than 1, it would not be properly updated on the server.

**Comment by TehNut** [comment]
Changing behavior that mods expect is equivalent to breaking it.

**Comment by Aaron1011** [comment]
@TehNut: After looking at the issue more, it appears that you were absolutely correct. This was indeed a bug in Sponge, and [has since been fixed](https://github.com/SpongePowered/SpongeForge/commit/ac4117187db3881fb3346d5d0f5f0b23eb0e284c).

Sorry to have wasted your time.
