### ISSUE TITLE
Startup crash

### ISSUE THREAD

**Issue by Akai1** [TehNut-Mods/Soul-Shards-The-Old-Ways#35]
#### Issue Description:
Game [crash](https://gist.github.com/Akai1/cb683af7238887a66f5b53238e350e62) on startup.

#### Affected Versions:

- Soul Shards: SoulShards-TOW-1.10.2-2.6.5-45
- Minecraft: 1.10.2
- Forge: 12.18.2.2125

**Comment by TehNut** [comment]
I have no clue where you got that version of TCon, and all the versions I looked at still had that method, but here, I guess...

**Comment by Akai1** [comment]
Thank you!
