### ISSUE TITLE
Elder Guardians are counted as guargians

### ISSUE THREAD

**Issue by ghost** [TehNut-Mods/Soul-Shards-The-Old-Ways#37]
Hi,

Elders guardians are counted as guardians, even if the spawn boss option is enabled. 

They should be counted as elder guardians.

Versions used:
SoulShards-TOW-1.10.2-2.6.6-46
Forge: 12.18.3.2185

**Comment by TehNut** [comment]
This is fixed in 1.11 due to how Mojang changed entity handling. I'll add (yet another) special case for 1.10

**Comment by TehNut** [comment]
![pic](http://i.imgur.com/guN7jwH.png)
