### ISSUE TITLE
Vanilla Spawner Crash

### ISSUE THREAD

**Issue by EndermanParty** [TehNut-Mods/Soul-Shards-The-Old-Ways#4]
I right clicked a soul shard that had a single wither skeleton kill in it on a Spider Spawner and it gave me this crash.
http://paste.ee/p/QZGtH

**Comment by EndermanParty** [comment]
If needed the spider spawner was one from Rougelike Dungeon.

**Comment by TehNut** [comment]
Dupe of #3 

Please update to the latest version. I fixed this yesterday.

**Comment by EndermanParty** [comment]
Alrighty thanks.
