### ISSUE TITLE
Multiblock Config

### ISSUE THREAD

**Issue by heidrifx** [TehNut-Mods/Soul-Shards-The-Old-Ways#40]
#### Issue Description:
Just wondering if editing the JSON File has any effect on the game. So far it doesn't appear to have. I changed all blocks to other blocks (Mod blocks, with Metadata). Now neither the original multi block, nor my edited one works. (Changed the catalyst item as well)

#### What happens:
Changes in the multipack.json don't have an effect in-game.

#### What you expected to happen:
Changed config should show effects. So if I want Birch Wood instead of Obsidian that should work.

#### Steps to reproduce:

1. Change any Block in the multi block.json to another Block (with Meta)
2. Changed the catalyst item as well (doesn't seem to effect the issue though)
3. -
...

____
#### Affected Versions (Do *not* use "latest"):

- Soul Shards: 2.6.7-48
- Minecraft: 1.10.2
- Forge: forge-12.18.3.2297

**Comment by Danymaddox** [comment]
Any news?

**Comment by TehNut** [comment]
Yes it was removed.

**Comment by Danymaddox** [comment]
So in the 1.10 version I cannot use metadata in the configs?
