### ISSUE TITLE
1.11.2 Tinkers Construct modifier missing

### ISSUE THREAD

**Issue by Caopr** [TehNut-Mods/Soul-Shards-The-Old-Ways#41]
#### Issue Description:

There is no "Soul Stealer" modifier in Tinkers Construct even when making sure the compatability check in the config is on.

____
#### Affected Versions (Do *not* use "latest"):

-Tinkers Construct 1.11.2-2.7.0.26
- Soul Shards: 1.11-2.6.6-47
- Minecraft: 1.11.2
- Forge:  1.11.2-13.20.0.2314

**Comment by TehNut** [comment]
Well there is no TCon compat in 1.11, so...

**Comment by Caopr** [comment]
Oh alright didint catch that. My apologies assumed it was due to it bieng in the config still
