### ISSUE TITLE
Crash on 1.12 (game won't start)

### ISSUE THREAD

**Issue by ghost** [TehNut-Mods/Soul-Shards-The-Old-Ways#42]
[crash-2017-06-15_14.24.29-client.txt](https://github.com/TehNut/Soul-Shards-The-Old-Ways/files/1077419/crash-2017-06-15_14.24.29-client.txt)
used forge 2327

**Comment by TehNut** [comment]
I need to update Forge

**Comment by CluelessPhil** [comment]
This happens on Forge 14.21.0.2239 and almost every single one too

**Comment by TehNut** [comment]
> \>\>\>***I***<<< need to update Forge.

**Comment by ghost** [comment]
hey ah, dunno if you fixed it or not but new version still crashes with forge 2333. just wanted to tell.
[crash-2017-06-17_21.51.30-client.txt](https://github.com/TehNut/Soul-Shards-The-Old-Ways/files/1082707/crash-2017-06-17_21.51.30-client.txt)
you need to update forge :D

**Comment by TehNut** [comment]
Did you bother reading that?
