### ISSUE TITLE
Not able to make Vile Dust

### ISSUE THREAD

**Issue by Kaisoul** [TehNut-Mods/Soul-Shards-The-Old-Ways#44]
#### Issue Description:
I can not find any recipe in the 1.12 version to make vile dust.

#### What happens:
not able to progress in the mod with out the ability to get vile dust.
Because there is no recipes to make vile dust.

#### What you expected to happen:
pop soul sand into a furnace and get vile dust...

#### Steps to reproduce:

1. load game with mod installed
2. notice there is no recipe to craft vile dust
...

____
#### Affected Versions (Do *not* use "latest"):
forge-1.12-14.21.1.2387
SoulShards-TOW-1.12-2.7.2-51
Minecraft 1.12

**Comment by TehNut** [comment]
Hm, I guess I never moved that to something that actually got called after the registry rewrite.
