### ISSUE TITLE
crash on world load SoulShards-TOW-1.12-2.7.3-52

### ISSUE THREAD

**Issue by IchigoGames** [TehNut-Mods/Soul-Shards-The-Old-Ways#45]
#### Issue Description:
it's in a modpack and i am the modpack author but i know its this mod thats crashing on world load

#### Steps to reproduce:

1. add SoulShards-TOW-1.12-2.7.3-52
2. use forge 2387
3. make a new world
...

____
#### Affected Versions (Do *not* use "latest"): SoulShards-TOW-1.12-2.7.3-52
crash report https://pastebin.com/0MiViZCq

- Soul Shards: 
- Minecraft: 
- Forge:

**Comment by TehNut** [comment]
And how exactly do you know it's SS?

**Comment by IchigoGames** [comment]
well i guse it could be something with SS but i updated SS and it crashed took it out and it loaded
