### ISSUE TITLE
Soulshard have no mob limit

### ISSUE THREAD

**Issue by Gh3ttoboy** [TehNut-Mods/Soul-Shards-The-Old-Ways#46]
**Whats happening:**
so i was just making a tier 5 soulshard and happend to see that the limit goes over 1024 to get a tier 5 well once i hit the 1600 mark i get a tier 5 shard but apperantly it has no limit i have a shard for the enderman thats 2728 and can still add more souls to it i have a gyazo picture of how the shard looks
the bar is blue and goes acros my screen and gets longer the more souls i add to it
[](https://i.gyazo.com/e4c4e8f3931c573640e6039086ae335c.png)

**What you expected to happen:**
Stop at the limit of mob souls in the shard

**Steps to reproduce:**
just keep killing creatures until you go over the 1600 mark

**Affected Versions:**
- Soul Shards: SoulShards-TOW-1.12-2.7.3-52
- Minecraft: 1.12.2
- Forge: Forge-14.23.0.2512

**Comment by TehNut** [comment]
I'm not able to reproduce this. It stops at 1024 as intended. Have you or the pack you are playing modified `../config/sstow/ShardTiers.json`?

**Comment by Gh3ttoboy** [comment]
apperantly the pack that im playing has changed the config didnt really think that would have been a thing in this pack (All The Mods 3) but they did it. so problem has been solved
  "5": {
    "minKills": 1600,
    "maxKills": 3200,
    "checkPlayer": false,
    "checkLight": false,
    "checkRedstone": true,
    "spawnAmount": 6,
    "cooldown": 2

Thanks for the quick response

**Comment by TehNut** [comment]
Well, a giant blue bar is still an issue. I'll take a look.

**Comment by TehNut** [comment]
Inform your modpack author that they need to fix their `ShardTiers.json` file. The final tier should have a `minKills` and `maxKills` of the same value.
