### ISSUE TITLE
Crash on game load

### ISSUE THREAD

**Issue by drewbit** [TehNut-Mods/Soul-Shards-The-Old-Ways#5]
Not sure what it means, here's the log:

http://paste.ee/p/ifpEP

**Comment by TehNut** [comment]
Did this happen after updating? Or just randomly started happening?

**Comment by TehNut** [comment]
TCon is causing it... Why would that break my item registration..? o.O

Edit: Or at least, it only happens if TCon is installed.

**Comment by drewbit** [comment]
Backdating to the previous version (SoulShards-TOW-1.8.9-2.2.1-7.jar) fixes the issue, so it's just the new version.

**Comment by drewbit** [comment]
Didn't happen randomly, just the new update.

**Comment by TehNut** [comment]
I see what the issue is.

**Comment by TehNut** [comment]
New build should be live on CurseForge in the next few minutes. Alternatively, you can grab it [here](http://tehnut.info/jenkins/job/SoulShardsTOW/job/1.8.9/).
