### ISSUE TITLE
Broken config

### ISSUE THREAD

**Issue by niklas2233** [TehNut-Mods/Soul-Shards-The-Old-Ways#51]
#### Issue Description:
when having the "Count mobs spawned by a Soul Cage towards Shard kills." on True it dosnt add on the soul shard. Or do this only work on like animals. and if it only work on animals i would like you to add it to every entity

#### What happens:

it dosnt add on the kills

#### What you expected to happen:

im expecting to see the kills go up on the soul shard but it dosnt

#### Steps to reproduce:

1. Enable the config.
2. Put the soul shard in the soul cage
3. And take it out and se that nothing has change on the soul shard
...

____
#### Affected Versions:

- Soul Shards: 1.12-2.7.4-53
- Minecraft: 1.12
- Forge: 14.23.1.2556

**Comment by TehNut** [comment]
What? No that isn't how it works. It means you can kill spawned entities and have them count towards the shard.
