### ISSUE TITLE
[1.12.2] Duribility past bar

### ISSUE THREAD

**Issue by Phonavis** [TehNut-Mods/Soul-Shards-The-Old-Ways#52]
#### Steps to reproduce:

1. Get a soul shard with past T5 souls
2. Observe
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- Soul Shards: 2.7.4-53
- Minecraft: 1.12.2
- Forge: 14.23.1.2568
- Server is running sponge if relevant
- Pretty sure the T5 number was edited in the config, running All the Mods 3, it's set at 1600 in the pack

**Comment by TehNut** [comment]
Can i see your tiers json file?
