### ISSUE TITLE
Tinker Modifier [1.12.2]

### ISSUE THREAD

**Issue by vertex101** [TehNut-Mods/Soul-Shards-The-Old-Ways#53]
#### Issue Description:
cant seem to find out how to make the tinkers modifier

____
#### Affected Versions (Do *not* use "latest"):

- Soul Shards: SoulShards-TOW-1.12-2.7.4-53
- Minecraft:  1.12.2
- Forge: 14.23.1.2594

**Comment by TehNut** [comment]
Re-added in https://github.com/TehNut/Soul-Shards-Respawn/commit/bd8327c607ce49c7b585e91dbba9972da97439b2 on [this](https://minecraft.curseforge.com/projects/soul-shards-respawn) Curse project.
