### ISSUE TITLE
Can't absorp spawners in modpack FS Lost Souls - Cause is identified

### ISSUE THREAD

**Issue by ThaDaVos** [TehNut-Mods/Soul-Shards-The-Old-Ways#54]
#### Issue Description:
I know this is an issue in a modpack, but it's probably a conflict between mods.
See issue: https://minecraft.curseforge.com/projects/forever-stranded-lost-souls/issues/160

It has to do with something SpawnerControl mod changes in the Vanilla Spawner which disables the ability to absorp spawners and have them look like pig spawners.

**Comment by TehNut** [comment]
I actually got a crash while testing this. Odd that you didn't.

**Comment by TehNut** [comment]
https://github.com/TehNut/Soul-Shards-The-Old-Ways/commit/5ec856fbd1afd9197ed1d7f35bae202b8e471403

**Comment by ThaDaVos** [comment]
Thanks for fixing this :D
Still strange you got a crash and I didn't

**Comment by ThaDaVos** [comment]
Please re-open, it's not fixed, still can't absorp spawners if default config of SpawnerControl is used and specific config option is true

**Comment by TehNut** [comment]
If it is still not fixed then this is not the problem. Create a new instance with just SS and SC and add mods until it stops working.

**Comment by ThaDaVos** [comment]
It only happens when AlterVanillaSpawner is set to true when using SpawnerControl so it has to be a conflict with SpawnerControl

**Comment by TehNut** [comment]
Well, again, I tested and it works fine. So you either didn't update Soul Shards, or it is another mod causing the issue.

**Comment by ThaDaVos** [comment]
Weird that it happens when you set a config to true in SpawnerControl

Currently using version 55 (updated 11 hours ago) when I updated it

**Comment by ThaDaVos** [comment]
Have you tried the FS Lost Souls pack?

**Comment by TehNut** [comment]
No. I tried with the mod. If it only happens in that modpack, then there another mod causing issues. So go figure out which one it is.

**Comment by TehNut** [comment]
And just to prove it to you even more, https://gfycat.com/RapidWeakBlacklab
