### ISSUE TITLE
Can't absorp spawners in modpack FS Lost Souls - Cause is identified - Continuation of #54

### ISSUE THREAD

**Issue by ThaDaVos** [TehNut-Mods/Soul-Shards-The-Old-Ways#55]
Continuation of https://github.com/TehNut/Soul-Shards-The-Old-Ways/issues/54 cause it's locked.

It's still not fixed - See https://gfycat.com/ImmaterialUnlinedApe
It works for Mobspawner with type - Pig, but others won't work.
Mobspawners of type Pig didn't work before you fixed it but now they do but the others don't work.
Except when you change the config on SpawnerControl to false.

**Comment by ThaDaVos** [comment]
To prove it's just these mods: https://gfycat.com/FlimsyConcernedGrayfox

**Comment by Pyrofab** [comment]
Could you provide the log file maybe?

**Comment by ThaDaVos** [comment]
I'll generate a clean one for you A.S.A.P.

**Comment by ThaDaVos** [comment]
[latest.log](https://github.com/TehNut/Soul-Shards-The-Old-Ways/files/1758691/latest.log)

There you go, what I did was->
1. Start game
2. Load world
3. Tried absorping blaze spawner twice, maybe thrice
4. Placed pig spawner and absorbed it, twice/thrice
5. Quit world
6. Quit game

**Comment by ThaDaVos** [comment]
So it's as clean as possible

**Comment by Pyrofab** [comment]
Next time I would advise you to do that in a fresh world and to put the log file on [gist](gist.github.com). This one was a pain to open on mobile and full of garbage as well. Anyway, I don't see anything wrong mentionning our mods so that will require further testing. Are you sure you tested with the updated version of Soul Shards ?

**Comment by ThaDaVos** [comment]
If you check the GIF you can see the version of the mod, I'm sorry for the way I uploaded the log.

The world is a fresh world - Created yesterday for the first test because of this.

The mod versions are: 
 - Soul Shards -> 1.12-2.7.5-55
 - SpawnerControl -> 1.2

**Comment by ThaDaVos** [comment]
![afbeelding](https://user-images.githubusercontent.com/5251028/36677265-0262caea-1b0e-11e8-88d3-f9dab73a8b0b.png)

**Comment by TehNut** [comment]
Should be solved with the rewrite on [this](https://minecraft.curseforge.com/projects/soul-shards-respawn) Curse project.
