### ISSUE TITLE
Textural issues with bound soulshards in creative + JEI

### ISSUE THREAD

**Issue by Sunconure11** [TehNut-Mods/Soul-Shards-The-Old-Ways#56]
#### Issue Description:
I'm noticing textural issues with bound soul shards in JEI + Creative.

#### What happens:

![screenshot 2018-02-28 14 23 27](https://user-images.githubusercontent.com/5614902/36808522-523f663c-1c93-11e8-9975-e3a6b330deed.png)

#### What you expected to happen:

No textural errors

#### Steps to reproduce:

1.  Turn on config settings to show bound soulshards
2. ???
3.  Profit
...

____
#### Affected Versions (Do *not* use "latest"):

- Soul Shards: 1.12-2.7.5-55
- Minecraft: 1.12.2
- Forge: 14.23.2.2623

#### Notes:

I am using TexFix and FoamFix.

**Comment by TehNut** [comment]
Not sure about this one off the top of my head. Are there any errors in the log? Does it happen without those 2 mods? Does it persist through a restart or is this only when the option is changed ingame?

**Comment by Sunconure11** [comment]
Haven't checked, but I'll go through those in the next few days.

I also tweaked the tiers and added some of my own.

**Comment by TehNut** [comment]
Oh, that's the issue. Use a resource pack to override the state json and add the new textures needed.
