### ISSUE TITLE
Broken texture on new tiers

### ISSUE THREAD

**Issue by Danymaddox** [TehNut-Mods/Soul-Shards-The-Old-Ways#57]
#### Issue Description:
Broken texture on custom tier

#### What happens:
I've creater custom tier Shards and every time one gets typed or evolved to the new tier the texture appears brocken

#### What you expected to happen:
A normal texture shard

#### Steps to reproduce:

1. Create one extra tier
2. Get that tier in game and kill one mob
3. There you have your broken texture
...

____
#### Affected Versions (Do *not* use "latest"):

- Soul Shards: 2.6.7
- Minecraft: 1.10.2
- Forge: 12.18.3.2511

**Comment by TehNut** [comment]
Override the state json with a resource pack and point it at new textures for the new tiers.
