### ISSUE TITLE
Ender Dragons spawned via Soul shards spawner dont work

### ISSUE THREAD

**Issue by zzBuilderzz** [TehNut-Mods/Soul-Shards-The-Old-Ways#59]
#### Issue Description:
ender dragon will not take damage when spawned form Soul shards spawner (note: I am using a mod called ender totem which prevents any and all ender dragons near by to be drawn in and be unable to move [requires a dragon egg to be right clicked upon the ender totem to function])

#### What happens:
Ender dragons spawn in,  but cant take any damage

#### What you expected to happen:

Ender dragons spawns in, and can take damage/be hit

#### Steps to reproduce:

1. obtain tier 5 ender dragon soul shard from creative (adjust relevant config option to true)
2. Place soul shard in soul shard spawner via right click
3. activate via redstone signal and wait for ender dragons to spawn
4. atempt to hit ender dragons
...

____
#### Affected Versions (Do *not* use "latest"):

- Soul Shards: 1.12-2.7.5-55.
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.2.2618

**Comment by TehNut** [comment]
There isn't really anything I can do about this. Dragons are extremely special cased in Vanilla. Boss mobs are disabled by default because I don't support them.
