### ISSUE TITLE
Soul Cage not responding to redstone signal

### ISSUE THREAD

**Issue by Periphera** [TehNut-Mods/Soul-Shards-The-Old-Ways#6]
1.8.9 v2.2.0-6

Is the soul cage activated/deactivated via redstone signal? If that is the intended behaviour, then it does not work in the above version. 

I know you have updated since, so was this fixed if that is the way it's supposed to work?

**Comment by TehNut** [comment]
With the default configs, only a Tier 5 shard responds to redstone.

**Comment by Periphera** [comment]
thanks for the info...would it be possible to add a config for lower tiered spawners to be redstone-controlled (there is no option in the current config).

**Comment by TehNut** [comment]
There already is. Look in `ShardTiers.json`.
