### ISSUE TITLE
Crash with EnderIO Cables in same block space

### ISSUE THREAD

**Issue by drewbit** [TehNut-Mods/Soul-Shards-The-Old-Ways#61]
#### Issue Description:
Placing a soul cage down with two enderio cable sharing the same block space causes the server to crash and continue to crash every time the world is loaded.

#### What happens:
When a soul cage has two different EnderIO cables sharing the same block space near it, it crashes the server.

#### What you expected to happen:
Regular interaction 

#### Steps to reproduce:

1. Place down soul cage
2. Place down redstone conduit underneath
3. Place down energy conduit (2nd tier) in same blockspace
...

____
#### Affected Versions (Do *not* use "latest"):

- Soul Shards: SoulShardsRespawn-1.12.2-1.0.5-7
- Minecraft: 1.12.2
- Forge: 14.23.4.2739

Log: https://paste.ee/p/0ZigE

**Comment by UpcraftLP** [comment]
idk if you noticed, but this does not mention `Soul Shards: The Old Ways` anywhere.
You can find the `Soul Shards: Respawn` repo [here](https://github.com/TehNut/Soul-Shards-Respawn "GitHub")

**Comment by TehNut** [comment]
Fixed by https://github.com/TehNut/Soul-Shards-Respawn/commit/bccaa374e70968cf9df2f21894c61d650da37d96
