### ISSUE TITLE
[Suggestion] Tinker's Construct modifier

### ISSUE THREAD

**Issue by angelnc1989** [TehNut-Mods/Soul-Shards-The-Old-Ways#62]
It would be cool to be able to add Soul Stealer to Tinker's Construct weapons.

**Comment by TehNut** [comment]
This is available in [Soul Shards Respawn](https://minecraft.curseforge.com/projects/soul-shards-respawn).

**Comment by angelnc1989** [comment]
Is this project discontinued?

**Comment by TehNut** [comment]
Yes, as stated on the Curse page.

**Comment by angelnc1989** [comment]
Thanks for the quick replies. Can I just switch the two versions or will I get issues in existing worlds?

**Comment by TehNut** [comment]
Sadly, no. The data structures have changed between the two versions since SSR is a full rewrite of SSTOW.
