### ISSUE TITLE
[Bug 1.8.9] Soul shard count does not increase on wither skeleton kill

### ISSUE THREAD

**Issue by SunnyTD** [TehNut-Mods/Soul-Shards-The-Old-Ways#8]
#### Steps to reproduce:
1. Have any empty soul shard in hot-bar
2. Equip weapon of choice
3. (Assuming in nether fortress) put down skeleton spawner
4. Kill wither skeleton once for soul shard identifier, then 2nd tome to observe bug. 
5. ???
6. Obtain bug. 

---
#### Affected Versions (Do _not_ use "latest"):
- Soul Shards: 2.2.3 and 2.2.5
- Minecraft: 1.8.9 
- Forge: 11.15.1.1764

**Comment by TehNut** [comment]
Should be available on Curse shortly. Otherwise, [here](http://tehnut.info/jenkins/job/SoulShardsTOW/job/1.8.9/).
